[tool.poetry]
name = "archive"
version = "0.1.0"
description = "Archive API"
authors = ["nicolevito <coemakeup@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "<5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
